### ISSUE TITLE
HoymilesZeroExport mit mehreren OpenDTU´s

### ISSUE THREAD

**Issue by 33aw33** [reserve85/HoymilesZeroExport#265]
Hallo,

Ist es möglich mehrere OpenDTU´s in dem Script zu definieren/konfigurieren?

Meine beiden Wechselrichter können nicht mit einer OpenDTU "versorgt" werden- Reichweite des Signals.

Vielen Dank für Rückmeldungen
aw

**Comment by reserve85** [comment]
sorry, ist nicht möglich. Es wird nur eine DTU unterstützt...

Gruß

**Comment by ghost** [comment]
Ich habe das mit Docker Compose gelöst. Die beiden kommen sich zwar ab und zu in die Quere, aber prinzipiell funktioniert es

```yaml
services:
  hoymileszeroexport_huette:
    image: ghcr.io/reserve85/hoymileszeroexport:main
    volumes:
      - ./HoymilesZeroExport_Config_Override_Huette.ini:/app/config.ini
    command: -c /app/config.ini
    restart: always

  hoymileszeroexport_garage:
    image: ghcr.io/reserve85/hoymileszeroexport:main
    volumes:
      - ./HoymilesZeroExport_Config_Override_Garage.ini:/app/config.ini
    command: -c /app/config.ini
    restart: always
```
